Repository Woom-s-Land/wooms-backend, pull requests merged in 2024-08, with the labels that each got.

#64 Feat : JWT Claim 데이터 추가
  src/main/java/com/ee06/wooms/global/config/SecurityConfig.java
  src/main/java/com/ee06/wooms/global/jwt/JWTUtil.java
  src/main/java/com/ee06/wooms/global/jwt/controller/ReIssueController.java
  src/main/java/com/ee06/wooms/global/jwt/filter/ChannelJoinFilter.java
  src/main/java/com/ee06/wooms/global/jwt/filter/LoginFilter.java
  src/main/java/com/ee06/wooms/global/jwt/service/JwtService.java
  src/main/java/com/ee06/wooms/global/oauth/CustomSuccessHandler.java
Labels: ✨ Feature

#65 Feat : 편지 작성
  src/main/java/com/ee06/wooms/domain/enrollments/repository/EnrollmentRepository.java
  src/main/java/com/ee06/wooms/domain/letters/controller/LetterController.java
  src/main/java/com/ee06/wooms/domain/letters/dto/NewLetterRequest.java
  src/main/java/com/ee06/wooms/domain/letters/entity/Letter.java
  src/main/java/com/ee06/wooms/domain/letters/entity/LetterController.java
  src/main/java/com/ee06/wooms/domain/letters/exception/LetterExceptionHandler.java
  src/main/java/com/ee06/wooms/domain/letters/exception/ex/NotInSameWoomsException.java
  src/main/java/com/ee06/wooms/domain/letters/repository/LetterRepository.java
  src/main/java/com/ee06/wooms/domain/letters/service/LetterService.java
  src/main/java/com/ee06/wooms/domain/wooms/controller/WoomsController.java
  src/main/java/com/ee06/wooms/global/exception/ErrorCode.java
Labels: ✨ Feature

#69 Config : AWS S3 추가
  .idea/modules.xml
  .idea/modules/wooms.main.iml
  build.gradle
  src/main/java/com/ee06/wooms/global/config/S3Config.java
Labels: ⚙️ Config

#71 Refactor : OAuth2 리다이렉트 경로 수정
  src/main/java/com/ee06/wooms/global/config/SecurityConfig.java
Labels: 🛠️ Refactor

#74 Feat : 편지 도메인 구현
  src/main/java/com/ee06/wooms/domain/letters/controller/LetterController.java
  src/main/java/com/ee06/wooms/domain/letters/dto/LetterDto.java
  src/main/java/com/ee06/wooms/domain/letters/entity/Letter.java
  src/main/java/com/ee06/wooms/domain/letters/exception/LetterExceptionHandler.java
  src/main/java/com/ee06/wooms/domain/letters/exception/ex/NotValidLetterException.java
  src/main/java/com/ee06/wooms/domain/letters/repository/LetterRepository.java
  src/main/java/com/ee06/wooms/domain/letters/service/LetterService.java
  src/main/java/com/ee06/wooms/domain/users/exception/UserExceptionHandler.java
  src/main/java/com/ee06/wooms/domain/users/exception/ex/UserNotAllowedException.java
  src/main/java/com/ee06/wooms/global/exception/ErrorCode.java
Labels: ✨ Feature

#73 Feat : 사연 기능 구현
  .idea/jarRepositories.xml
  build.gradle
  src/main/java/com/ee06/wooms/domain/stories/Script.java
  src/main/java/com/ee06/wooms/domain/stories/controller/StoryController.java
  src/main/java/com/ee06/wooms/domain/stories/dto/StoryResponse.java
  src/main/java/com/ee06/wooms/domain/stories/dto/StoryWriteRequest.java
  src/main/java/com/ee06/wooms/domain/stories/entity/Story.java
  src/main/java/com/ee06/wooms/domain/stories/repository/StoryRepository.java
  src/main/java/com/ee06/wooms/domain/stories/service/StoryService.java
  src/main/java/com/ee06/wooms/global/ai/exception/AIExceptionHandler.java
  src/main/java/com/ee06/wooms/global/ai/exception/FailedConvertFileException.java
  src/main/java/com/ee06/wooms/global/ai/exception/FailedRequestToGptException.java
  src/main/java/com/ee06/wooms/global/ai/service/AIService.java
  src/main/java/com/ee06/wooms/global/aws/exception/FileUploadFailedException.java
  src/main/java/com/ee06/wooms/global/aws/service/S3Service.java
  src/main/java/com/ee06/wooms/global/config/OpenAIConfig.java
  src/main/java/com/ee06/wooms/global/config/SecurityConfig.java
  src/main/java/com/ee06/wooms/global/exception/ErrorCode.java
  src/main/java/com/ee06/wooms/global/jwt/service/JwtService.java
  src/main/java/com/ee06/wooms/global/util/PromptUtils.java
Labels: ✨ Feature

#77 Feat : Wooms map 색상 설정
  src/main/java/com/ee06/wooms/domain/letters/service/LetterService.java
  src/main/java/com/ee06/wooms/domain/wooms/controller/WoomsController.java
  src/main/java/com/ee06/wooms/domain/wooms/dto/WoomsDto.java
  src/main/java/com/ee06/wooms/domain/wooms/entity/MapColorStatus.java
  src/main/java/com/ee06/wooms/domain/wooms/entity/Wooms.java
  src/main/java/com/ee06/wooms/domain/wooms/service/WoomsService.java
Labels: ✨ Feature

#80 Docs : 스웨거 문서 작성
  src/main/java/com/ee06/wooms/domain/letters/controller/LetterController.java
  src/main/java/com/ee06/wooms/domain/wooms/controller/WoomsController.java
  src/main/java/com/ee06/wooms/domain/wooms/dto/WoomsEnrollRequest.java
  src/main/java/com/ee06/wooms/domain/wooms/dto/WoomsMandateAdminRequest.java
  src/main/java/com/ee06/wooms/domain/wooms/service/WoomsService.java
Labels: 📕 Documentation

#81 Feat: 서블릿 Cors, Cookie SameSite 설정
  src/main/java/com/ee06/wooms/global/config/WebConfig.java
  src/main/java/com/ee06/wooms/global/config/filter/CorsFilter.java
  src/main/java/com/ee06/wooms/global/jwt/filter/ChannelJoinFilter.java
  src/main/java/com/ee06/wooms/global/jwt/filter/CustomLogoutFilter.java
  src/main/java/com/ee06/wooms/global/jwt/filter/JWTFilter.java
  src/main/java/com/ee06/wooms/global/jwt/filter/LoginFilter.java
  src/main/java/com/ee06/wooms/global/jwt/service/JwtService.java
  src/main/java/com/ee06/wooms/global/oauth/CustomSuccessHandler.java
  src/main/java/com/ee06/wooms/global/util/CookieUtils.java
Labels: ✨ Feature

#83 Feat : 사연 검증
  src/main/java/com/ee06/wooms/domain/stories/Script.java
  src/main/java/com/ee06/wooms/domain/stories/controller/StoryController.java
  src/main/java/com/ee06/wooms/domain/stories/dto/StoryWriteRequest.java
  src/main/java/com/ee06/wooms/domain/stories/service/StoryService.java
  src/main/java/com/ee06/wooms/global/ai/service/AIService.java
  src/main/java/com/ee06/wooms/global/aws/FileFormat.java
  src/main/java/com/ee06/wooms/global/aws/exception/AwsExceptionHandler.java
  src/main/java/com/ee06/wooms/global/aws/service/S3Service.java
  src/main/java/com/ee06/wooms/global/config/SecurityConfig.java
  src/main/java/com/ee06/wooms/global/jwt/filter/JWTFilter.java
Labels: ✨ Feature

#84 Config#82
  build.gradle
  src/main/java/com/ee06/wooms/domain/letters/controller/LetterController.java
  src/main/java/com/ee06/wooms/global/config/SecurityConfig.java
Labels: ⚙️ Config

#86 feat : 편지 작성 날짜 시간 반환
  src/main/java/com/ee06/wooms/domain/letters/dto/LetterDto.java
  src/main/java/com/ee06/wooms/domain/letters/service/LetterService.java
Labels: ✨ Feature

#88 Feat : 초대코드 사용한 Wooms 이름 반환 구현, 신청리스트 페이징 구현
  src/main/java/com/ee06/wooms/domain/enrollments/repository/EnrollmentRepository.java
  src/main/java/com/ee06/wooms/domain/wooms/controller/WoomsController.java
  src/main/java/com/ee06/wooms/domain/wooms/exception/WoomsExceptionHandler.java
  src/main/java/com/ee06/wooms/domain/wooms/exception/ex/WoomsEnrollmentLimitExceededException.java
  src/main/java/com/ee06/wooms/domain/wooms/service/WoomsService.java
  src/main/java/com/ee06/wooms/global/exception/ErrorCode.java
  src/main/resources/application-prod.properties
  src/main/resources/application.properties
Labels: ✨ Feature

#91 Feat : 사연 도메인 추가 기능
  src/main/java/com/ee06/wooms/domain/stories/dto/StoryResponse.java
  src/main/java/com/ee06/wooms/domain/stories/dto/StoryWriteRequest.java
  src/main/java/com/ee06/wooms/domain/stories/repository/StoryRepository.java
  src/main/java/com/ee06/wooms/domain/stories/service/StoryService.java
  src/main/java/com/ee06/wooms/domain/users/repository/UserRepository.java
Labels: ✨ Feature

#92 Feat : 그룹(Wooms) 탈퇴
  src/main/java/com/ee06/wooms/domain/enrollments/repository/EnrollmentRepository.java
  src/main/java/com/ee06/wooms/domain/wooms/controller/WoomsController.java
  src/main/java/com/ee06/wooms/domain/wooms/exception/WoomsExceptionHandler.java
  src/main/java/com/ee06/wooms/domain/wooms/exception/ex/WoomsLeaderNotLeftWoomsException.java
  src/main/java/com/ee06/wooms/domain/wooms/repository/WoomsRepository.java
  src/main/java/com/ee06/wooms/domain/wooms/service/WoomsService.java
  src/main/java/com/ee06/wooms/global/config/SecurityConfig.java
  src/main/java/com/ee06/wooms/global/exception/ErrorCode.java
Labels: ✨ Feature

#94 Config : Security H2 수정
  src/main/java/com/ee06/wooms/global/config/SecurityConfig.java
Labels: ⚙️ Config

#96 Refactor : 사연 도메인 예외 수정
  src/main/java/com/ee06/wooms/domain/stories/controller/StoryController.java
  src/main/java/com/ee06/wooms/domain/stories/service/StoryService.java
  src/main/java/com/ee06/wooms/domain/wooms/exception/WoomsExceptionHandler.java
  src/main/java/com/ee06/wooms/domain/wooms/exception/ex/WoomsNotAllowedUserException.java
  src/main/java/com/ee06/wooms/global/exception/ErrorCode.java
Labels: 🛠️ Refactor, ✨ Feature

#99 Feat : 사진 도메인
  src/main/java/com/ee06/wooms/domain/comments/repository/CommentRepository.java
  src/main/java/com/ee06/wooms/domain/enrollments/entity/Enrollment.java
  src/main/java/com/ee06/wooms/domain/enrollments/repository/EnrollmentRepository.java
  src/main/java/com/ee06/wooms/domain/photos/controller/PhotoController.java
  src/main/java/com/ee06/wooms/domain/photos/dto/PhotoDetailsResponse.java
  src/main/java/com/ee06/wooms/domain/photos/dto/PhotoRequest.java
  src/main/java/com/ee06/wooms/domain/photos/dto/PhotoResponse.java
  src/main/java/com/ee06/wooms/domain/photos/entity/Photo.java
  src/main/java/com/ee06/wooms/domain/photos/entity/WoomsPhotoFlipped.java
  src/main/java/com/ee06/wooms/domain/photos/exception/PhotoExceptionHandler.java
  src/main/java/com/ee06/wooms/domain/photos/exception/ex/FailedCreatePhotoException.java
  src/main/java/com/ee06/wooms/domain/photos/exception/ex/NotFoundPhotoException.java
  src/main/java/com/ee06/wooms/domain/photos/exception/ex/NotMatchedUserException.java
  src/main/java/com/ee06/wooms/domain/photos/exception/ex/NotMatchedWoomsException.java
  src/main/java/com/ee06/wooms/domain/photos/repository/PhotoRepository.java
  src/main/java/com/ee06/wooms/domain/photos/service/PhotoService.java
  src/main/java/com/ee06/wooms/global/exception/ErrorCode.java
Labels: ✨ Feature

#105 Feat : 픽셀 맵
  src/main/java/com/ee06/wooms/domain/photos/controller/PhotoController.java
  src/main/java/com/ee06/wooms/domain/photos/dto/MapResponse.java
  src/main/java/com/ee06/wooms/domain/photos/repository/PhotoRepository.java
  src/main/java/com/ee06/wooms/domain/photos/service/PhotoService.java
Labels: ✨ Feature

#108 Feat : wooms info 반환시 wooms 리더 반환
  src/main/java/com/ee06/wooms/domain/wooms/dto/WoomsDto.java
  src/main/java/com/ee06/wooms/domain/wooms/entity/Wooms.java
  src/main/java/com/ee06/wooms/domain/wooms/service/WoomsService.java
Labels: ✨ Feature

#106 Feat : 작업 대기 큐 기능
  src/main/java/com/ee06/wooms/WoomsApplication.java
  src/main/java/com/ee06/wooms/domain/stories/service/StoryService.java
  src/main/java/com/ee06/wooms/global/ai/dto/RequestCallback.java
  src/main/java/com/ee06/wooms/global/ai/dto/TTSRequest.java
  src/main/java/com/ee06/wooms/global/ai/exception/AIExceptionHandler.java
  src/main/java/com/ee06/wooms/global/ai/exception/ex/FailedConvertFileException.java
  src/main/java/com/ee06/wooms/global/ai/exception/ex/FailedRequestToGptException.java
  src/main/java/com/ee06/wooms/global/ai/exception/ex/FailedSwitchStateException.java
  src/main/java/com/ee06/wooms/global/ai/service/QueueService.java
  src/main/java/com/ee06/wooms/global/exception/ErrorCode.java
Labels: ✨ Feature

#111 Feat : Wooms 페이징 구현
  src/main/java/com/ee06/wooms/domain/letters/repository/LetterRepository.java
  src/main/java/com/ee06/wooms/domain/wooms/controller/WoomsController.java
  src/main/java/com/ee06/wooms/domain/wooms/repository/WoomsRepository.java
  src/main/java/com/ee06/wooms/domain/wooms/service/WoomsService.java
Labels: ✨ Feature

#113 Refactor : 로그아웃 기능 수정
  src/main/java/com/ee06/wooms/domain/stories/service/StoryService.java
  src/main/java/com/ee06/wooms/domain/users/service/UserService.java
  src/main/java/com/ee06/wooms/global/jwt/filter/CustomLogoutFilter.java
Labels: 🛠️ Refactor

#115 Feat : 특정 그룹의 관리자 여부 확인
  src/main/java/com/ee06/wooms/domain/wooms/controller/WoomsController.java
  src/main/java/com/ee06/wooms/domain/wooms/service/WoomsService.java
Labels: ✨ Feature

#119 feat : User 정보 조회시 Uuid 반환
  src/main/java/com/ee06/wooms/domain/users/dto/auth/UserGameInfo.java
  src/main/java/com/ee06/wooms/domain/users/service/UserService.java
Labels: ✨ Feature

#121 Refacotr : 방명록 조회 시 사용자 costume 누락 수정
  src/main/java/com/ee06/wooms/domain/comments/entity/Comment.java
Labels: 🛠️ Refactor

#122 Feat : 채팅 서버 및 게임 서버 구현
  src/main/java/com/ee06/wooms/domain/chat/ChannelRepository.java
  src/main/java/com/ee06/wooms/domain/chat/SessionRepository.java
  src/main/java/com/ee06/wooms/domain/chat/common/ChannelDisconnectListener.java
  src/main/java/com/ee06/wooms/domain/chat/common/ChatInterceptor.java
  src/main/java/com/ee06/wooms/domain/chat/common/WebSocketConfig.java
  src/main/java/com/ee06/wooms/domain/chat/controller/ChatController.java
  src/main/java/com/ee06/wooms/domain/chat/dto/ChatMessage.java
  src/main/java/com/ee06/wooms/domain/chat/dto/MoveRequest.java
  src/main/java/com/ee06/wooms/domain/chat/dto/MoveResponse.java
  src/main/java/com/ee06/wooms/domain/chat/entity/Channel.java
  src/main/java/com/ee06/wooms/domain/chat/entity/Woom.java
  src/main/java/com/ee06/wooms/domain/chat/exception/StompError.java
  src/main/java/com/ee06/wooms/domain/chat/exception/StompErrorHandler.java
  src/main/java/com/ee06/wooms/global/config/SecurityConfig.java
  src/main/java/com/ee06/wooms/global/jwt/JWTUtil.java
Labels: ✨ Feature

#124 Refactor : 사용자 costume 값 수정
  src/main/java/com/ee06/wooms/global/util/RandomHelper.java
Labels: ✨ Feature

#127 Refactor : Cors 와일드 카드 수정
  .idea/misc.xml
  src/main/java/com/ee06/wooms/global/config/CorsConfig.java
  src/main/java/com/ee06/wooms/global/config/filter/CorsFilter.java
Labels: 🛠️ Refactor

#130 Feat : photo Response 컬럼 추가
  src/main/java/com/ee06/wooms/domain/photos/dto/PhotoResponse.java
  src/main/java/com/ee06/wooms/domain/photos/service/PhotoService.java
Labels: ✨ Feature

#132 Feat : 만료된 요청 시 토큰 재발급
  src/main/java/com/ee06/wooms/domain/comments/controller/CommentController.java
  src/main/java/com/ee06/wooms/domain/stories/controller/StoryController.java
  src/main/java/com/ee06/wooms/global/exception/ErrorCode.java
  src/main/java/com/ee06/wooms/global/jwt/JWTUtil.java
  src/main/java/com/ee06/wooms/global/jwt/exception/ExpiredRefreshTokenException.java
  src/main/java/com/ee06/wooms/global/jwt/exception/JwtExceptionHandler.java
  src/main/java/com/ee06/wooms/global/jwt/exception/ReIssueTokenResponse.java
  src/main/java/com/ee06/wooms/global/jwt/filter/JWTFilter.java
  src/main/java/com/ee06/wooms/global/jwt/service/JwtService.java
Labels: ✨ Feature

#133 Feat : 내가 속한 Wooms 조회
  src/main/java/com/ee06/wooms/domain/wooms/controller/WoomsController.java
  src/main/java/com/ee06/wooms/domain/wooms/entity/Wooms.java
  src/main/java/com/ee06/wooms/domain/wooms/repository/WoomsRepository.java
  src/main/java/com/ee06/wooms/domain/wooms/service/WoomsService.java
Labels: ✨ Feature

#136 Feat#135
  src/main/java/com/ee06/wooms/domain/photos/controller/PhotoController.java
  src/main/java/com/ee06/wooms/domain/photos/service/PhotoService.java
Labels: 🛠️ Refactor

#138 Feat : 읽지 않은 편지 수 계산
  src/main/java/com/ee06/wooms/domain/letters/controller/LetterController.java
  src/main/java/com/ee06/wooms/domain/letters/dto/LetterUnreadDto.java
  src/main/java/com/ee06/wooms/domain/letters/repository/LetterRepository.java
  src/main/java/com/ee06/wooms/domain/letters/service/LetterService.java
Labels: ✨ Feature

#139 Refactor : LocalDateTime 변경
  src/main/java/com/ee06/wooms/domain/photos/repository/PhotoRepository.java
  src/main/java/com/ee06/wooms/domain/photos/service/PhotoService.java
Labels: 🛠️ Refactor

#142 Feat : 소켓 채널 인증
  src/main/java/com/ee06/wooms/domain/chat/common/CustomHandshakeInterceptor.java
  src/main/java/com/ee06/wooms/domain/photos/controller/PhotoController.java
  src/main/java/com/ee06/wooms/domain/photos/repository/PhotoRepository.java
  src/main/java/com/ee06/wooms/domain/photos/service/PhotoService.java
Labels: 🛠️ Refactor

#144 Refactor : woomsId 추가
  src/main/java/com/ee06/wooms/domain/photos/repository/PhotoRepository.java
Labels: 🛠️ Refactor

#146 Feat : 사용자 인증
  src/main/java/com/ee06/wooms/domain/users/controller/UserController.java
  src/main/java/com/ee06/wooms/global/exception/ErrorCode.java
Labels: ✨ Feature

#148 Refactor : 사진관 월 대표 사진 변경
  src/main/java/com/ee06/wooms/domain/photos/repository/PhotoRepository.java
Labels: 🛠️ Refactor

#150 Refactor : ChatGpt Prompt 수정, 방명록 글자 수 수정
  src/main/java/com/ee06/wooms/domain/comments/dto/CommentRequest.java
  src/main/java/com/ee06/wooms/global/ai/service/AIService.java
  src/main/resources/application-prod.properties
  src/main/resources/application.properties
Labels: 🛠️ Refactor

#154 Refactor : 사진 조회 시 페이지네이션 수정
  src/main/java/com/ee06/wooms/domain/photos/repository/PhotoRepository.java
  src/main/java/com/ee06/wooms/global/config/OpenAIConfig.java
Labels: 🛠️ Refactor

#156 Feat : 특정 기간, 키워드 별 사연 목록 조회
  src/main/java/com/ee06/wooms/domain/stories/controller/StoryController.java
  src/main/java/com/ee06/wooms/domain/stories/dto/StorySearchCriteria.java
  src/main/java/com/ee06/wooms/domain/stories/repository/StoryRepository.java
  src/main/java/com/ee06/wooms/domain/stories/service/StoryService.java
Labels: ✨ Feature
