Repository Woom-s-Land/wooms-backend, pull requests merged in 2024-07, with the labels that each got.

#2 Feat : BaseTimeEntity 적용
  src/main/java/com/ee06/wooms/domain/comments/entity/Comment.java
  src/main/java/com/ee06/wooms/domain/enrollments/entity/Enrollment.java
  src/main/java/com/ee06/wooms/domain/letters/entity/Letter.java
  src/main/java/com/ee06/wooms/domain/photos/entity/Photo.java
  src/main/java/com/ee06/wooms/domain/stories/entity/Story.java
  src/main/java/com/ee06/wooms/domain/users/entity/User.java
  src/main/java/com/ee06/wooms/domain/wooms/entity/Wooms.java
  src/main/java/com/ee06/wooms/global/audit/AuditingConfig.java
  src/main/java/com/ee06/wooms/global/audit/BaseTimeEntity.java
Labels: ✨ Feature

#4 Feat : 소셜 로그인 구현
  build.gradle
  src/main/java/com/ee06/wooms/domain/enrollments/entity/Enrollment.java
  src/main/java/com/ee06/wooms/domain/users/dto/CustomOAuth2User.java
  src/main/java/com/ee06/wooms/domain/users/dto/GithubResponse.java
  src/main/java/com/ee06/wooms/domain/users/dto/GoogleResponse.java
  src/main/java/com/ee06/wooms/domain/users/dto/OAuth2Response.java
  src/main/java/com/ee06/wooms/domain/users/entity/User.java
  src/main/java/com/ee06/wooms/domain/users/repository/UserRepository.java
  src/main/java/com/ee06/wooms/domain/users/service/CustomOAuth2UserService.java
  src/main/java/com/ee06/wooms/global/jwt/JWTUtil.java
  src/main/java/com/ee06/wooms/global/jwt/dto/ErrorCode.java
  src/main/java/com/ee06/wooms/global/jwt/dto/ErrorResponse.java
  src/main/java/com/ee06/wooms/global/jwt/dto/Token.java
  src/main/java/com/ee06/wooms/global/jwt/filter/JWTFilter.java
  src/main/java/com/ee06/wooms/global/oauth/CustomSuccessHandler.java
  src/main/java/com/ee06/wooms/global/oauth/exception/NotFoundPlatformException.java
  src/main/java/com/ee06/wooms/global/security/SecurityConfig.java
Labels: ✨ Feature

#11 Config#10 : CICD 설정
  Jenkinsfile
  docker-compose.yml
Labels: ⚙️ Config

#14 Config : application.properties 설정
  .idea/compiler.xml
  .idea/material_theme_project_new.xml
  src/main/resources/application-dev.properties
  src/main/resources/application-prod.properties
  src/main/resources/application.properties
Labels: ✨ Feature

#18 Feat : 일반 사용자 관련 기능 개발
  .idea/misc.xml
  build.gradle
  src/main/java/com/ee06/wooms/domain/letters/entity/LetterController.java
  src/main/java/com/ee06/wooms/domain/users/controller/UserController.java
  src/main/java/com/ee06/wooms/domain/users/dto/CustomUserDetails.java
  src/main/java/com/ee06/wooms/domain/users/dto/auth/Join.java
  src/main/java/com/ee06/wooms/domain/users/dto/auth/Login.java
  src/main/java/com/ee06/wooms/domain/users/dto/oauth/CustomOAuth2User.java
  src/main/java/com/ee06/wooms/domain/users/dto/oauth/GithubResponse.java
  src/main/java/com/ee06/wooms/domain/users/dto/oauth/GoogleResponse.java
  src/main/java/com/ee06/wooms/domain/users/dto/oauth/OAuth2Response.java
  src/main/java/com/ee06/wooms/domain/users/entity/User.java
  src/main/java/com/ee06/wooms/domain/users/exception/UserEmailNotFoundException.java
  src/main/java/com/ee06/wooms/domain/users/exception/UserExceptionHandler.java
  src/main/java/com/ee06/wooms/domain/users/exception/UserExistException.java
  src/main/java/com/ee06/wooms/domain/users/repository/UserRepository.java
  src/main/java/com/ee06/wooms/domain/users/service/CustomOAuth2UserService.java
  src/main/java/com/ee06/wooms/domain/users/service/UserService.java
  src/main/java/com/ee06/wooms/global/common/CommonResponse.java
  src/main/java/com/ee06/wooms/global/config/CorsConfig.java
  src/main/java/com/ee06/wooms/global/config/RedisConfig.java
  src/main/java/com/ee06/wooms/global/config/SecurityConfig.java
  src/main/java/com/ee06/wooms/global/exception/ErrorCode.java
  src/main/java/com/ee06/wooms/global/exception/ErrorResponse.java
  src/main/java/com/ee06/wooms/global/jwt/JWTUtil.java
  src/main/java/com/ee06/wooms/global/jwt/controller/ReIssueController.java
  src/main/java/com/ee06/wooms/global/jwt/dto/ErrorCode.java
  src/main/java/com/ee06/wooms/global/jwt/dto/RefreshToken.java
  src/main/java/com/ee06/wooms/global/jwt/exception/InvalidRefreshTokenException.java
  src/main/java/com/ee06/wooms/global/jwt/exception/InvalidTokenException.java
  src/main/java/com/ee06/wooms/global/jwt/exception/JwtExceptionHandler.java
  src/main/java/com/ee06/wooms/global/jwt/filter/CustomLogoutFilter.java
  src/main/java/com/ee06/wooms/global/jwt/filter/JWTFilter.java
  src/main/java/com/ee06/wooms/global/jwt/filter/LoginFilter.java
  src/main/java/com/ee06/wooms/global/jwt/repository/RefreshTokenRepository.java
  src/main/java/com/ee06/wooms/global/jwt/service/JwtService.java
  src/main/java/com/ee06/wooms/global/oauth/CustomSuccessHandler.java
  src/main/java/com/ee06/wooms/global/oauth/exception/NotFoundPlatformException.java
  src/main/java/com/ee06/wooms/global/util/ErrorCodeUtils.java
  src/main/java/com/ee06/wooms/global/util/RandomHelper.java
Labels: ✨ Feature

#21 Config : 스웨거 의존성 추가
  build.gradle
  src/main/java/com/ee06/wooms/global/config/SecurityConfig.java
  src/main/java/com/ee06/wooms/global/config/SwaggerConfig.java
Labels: ⚙️ Config

#27 Feat : 사용자 Menu 기능 개발
  src/main/java/com/ee06/wooms/domain/users/controller/UserController.java
  src/main/java/com/ee06/wooms/domain/users/dto/CustomUserDetails.java
  src/main/java/com/ee06/wooms/domain/users/dto/UserGameInfo.java
  src/main/java/com/ee06/wooms/domain/users/entity/User.java
  src/main/java/com/ee06/wooms/domain/users/exception/UserExceptionHandler.java
  src/main/java/com/ee06/wooms/domain/users/exception/UserNotFoundException.java
  src/main/java/com/ee06/wooms/domain/users/service/UserService.java
  src/main/java/com/ee06/wooms/global/config/SecurityConfig.java
  src/main/java/com/ee06/wooms/global/exception/ErrorCode.java
  src/main/java/com/ee06/wooms/global/jwt/filter/JWTFilter.java
Labels: ✨ Feature

#28 Feat : 이메일 인증 기능 개발
  build.gradle
  src/main/java/com/ee06/wooms/domain/users/controller/UserController.java
  src/main/java/com/ee06/wooms/domain/users/entity/Mail.java
  src/main/java/com/ee06/wooms/domain/users/exception/UserExceptionHandler.java
  src/main/java/com/ee06/wooms/domain/users/exception/ex/UserEmailCodeNotMatchedException.java
  src/main/java/com/ee06/wooms/domain/users/exception/ex/UserEmailExpiredException.java
  src/main/java/com/ee06/wooms/domain/users/exception/ex/UserEmailNotFoundException.java
  src/main/java/com/ee06/wooms/domain/users/exception/ex/UserExistException.java
  src/main/java/com/ee06/wooms/domain/users/exception/ex/UserNotFoundException.java
  src/main/java/com/ee06/wooms/domain/users/exception/ex/UserNotSentEmailException.java
  src/main/java/com/ee06/wooms/domain/users/repository/MailRepository.java
  src/main/java/com/ee06/wooms/domain/users/service/CustomOAuth2UserService.java
  src/main/java/com/ee06/wooms/domain/users/service/UserService.java
  src/main/java/com/ee06/wooms/global/config/SecurityConfig.java
  src/main/java/com/ee06/wooms/global/exception/ErrorCode.java
  src/main/java/com/ee06/wooms/global/util/RandomHelper.java
Labels: ✨ Feature

#30 Feat : 그룹 생성 기능
  src/main/java/com/ee06/wooms/domain/comments/entity/Comment.java
  src/main/java/com/ee06/wooms/domain/enrollments/entity/Enrollment.java
  src/main/java/com/ee06/wooms/domain/enrollments/repository/EnrollmentRepository.java
  src/main/java/com/ee06/wooms/domain/photos/entity/Photo.java
  src/main/java/com/ee06/wooms/domain/stories/entity/Story.java
  src/main/java/com/ee06/wooms/domain/users/exception/ex/UserNotFoundException.java
  src/main/java/com/ee06/wooms/domain/users/service/UserService.java
  src/main/java/com/ee06/wooms/domain/wooms/controller/WoomController.java
  src/main/java/com/ee06/wooms/domain/wooms/dto/WoomCreateRequestDto.java
  src/main/java/com/ee06/wooms/domain/wooms/dto/WoomDto.java
  src/main/java/com/ee06/wooms/domain/wooms/entity/Wooms.java
  src/main/java/com/ee06/wooms/domain/wooms/repository/WoomRepository.java
  src/main/java/com/ee06/wooms/domain/wooms/service/WoomService.java
  src/main/resources/application-dev.properties
Labels: ✨ Feature

#33 Refactor : 사용자 관련 리팩토링
  src/main/java/com/ee06/wooms/domain/users/dto/auth/Join.java
  src/main/java/com/ee06/wooms/domain/users/entity/User.java
  src/main/java/com/ee06/wooms/domain/users/service/UserService.java
  src/main/java/com/ee06/wooms/global/jwt/JWTUtil.java
  src/main/java/com/ee06/wooms/global/jwt/filter/JWTFilter.java
  src/main/java/com/ee06/wooms/global/jwt/filter/LoginFilter.java
  src/main/java/com/ee06/wooms/global/jwt/service/JwtService.java
  src/main/java/com/ee06/wooms/global/oauth/CustomSuccessHandler.java
Labels: 🛠️ Refactor

#35 Refactor : 그룹 생성 반환값 변경
  src/main/java/com/ee06/wooms/domain/wooms/controller/WoomController.java
  src/main/java/com/ee06/wooms/domain/wooms/entity/Wooms.java
  src/main/java/com/ee06/wooms/domain/wooms/service/WoomService.java
Labels: 🛠️ Refactor

#37 Refactor : OAuth 로그인 유저 토큰 값 수정
  src/main/java/com/ee06/wooms/domain/users/dto/oauth/CustomOAuth2User.java
  src/main/java/com/ee06/wooms/global/oauth/CustomSuccessHandler.java
Labels: 🛠️ Refactor

#38 Feat : Wooms 의 Woom 리스트 조회
  src/main/java/com/ee06/wooms/domain/enrollments/repository/EnrollmentRepository.java
  src/main/java/com/ee06/wooms/domain/wooms/controller/WoomController.java
  src/main/java/com/ee06/wooms/domain/wooms/controller/WoomsController.java
  src/main/java/com/ee06/wooms/domain/wooms/dto/WoomsCreateRequestDto.java
  src/main/java/com/ee06/wooms/domain/wooms/dto/WoomsDto.java
  src/main/java/com/ee06/wooms/domain/wooms/dto/woomsInfoDto.java
  src/main/java/com/ee06/wooms/domain/wooms/entity/Wooms.java
  src/main/java/com/ee06/wooms/domain/wooms/repository/WoomRepository.java
  src/main/java/com/ee06/wooms/domain/wooms/repository/WoomsRepository.java
  src/main/java/com/ee06/wooms/domain/wooms/service/WoomService.java
  src/main/java/com/ee06/wooms/domain/wooms/service/WoomsService.java
Labels: ✨ Feature

#40 BindingError 추가
  src/main/java/com/ee06/wooms/global/exception/BindingException.java
  src/main/java/com/ee06/wooms/global/exception/ErrorCode.java
  src/main/java/com/ee06/wooms/global/exception/GlobalExceptionHandler.java
  src/main/java/com/ee06/wooms/global/util/ErrorCodeUtils.java
Labels: ✨ Feature

#41 Feat : 그룹 참여 기능 구현
  src/main/java/com/ee06/wooms/domain/enrollments/repository/EnrollmentRepository.java
  src/main/java/com/ee06/wooms/domain/wooms/controller/WoomsController.java
  src/main/java/com/ee06/wooms/domain/wooms/exception/WoomsExceptionHandler.java
  src/main/java/com/ee06/wooms/domain/wooms/exception/ex/WoomsAlreadyMemberException.java
  src/main/java/com/ee06/wooms/domain/wooms/exception/ex/WoomsAlreadyWaitingException.java
  src/main/java/com/ee06/wooms/domain/wooms/exception/ex/WoomsNotValidInviteCodeException.java
  src/main/java/com/ee06/wooms/domain/wooms/repository/WoomsRepository.java
  src/main/java/com/ee06/wooms/domain/wooms/service/WoomsService.java
  src/main/java/com/ee06/wooms/global/exception/ErrorCode.java
Labels: ✨ Feature

#43 Feat : Wooms 상세 조회
  src/main/java/com/ee06/wooms/domain/enrollments/entity/Enrollment.java
  src/main/java/com/ee06/wooms/domain/enrollments/repository/EnrollmentRepository.java
  src/main/java/com/ee06/wooms/domain/users/dto/UserInfoDto.java
  src/main/java/com/ee06/wooms/domain/users/entity/User.java
  src/main/java/com/ee06/wooms/domain/wooms/controller/WoomsController.java
  src/main/java/com/ee06/wooms/domain/wooms/dto/WoomsDetailInfoDto.java
  src/main/java/com/ee06/wooms/domain/wooms/dto/WoomsInfoDto.java
  src/main/java/com/ee06/wooms/domain/wooms/exception/WoomsExceptionHandler.java
  src/main/java/com/ee06/wooms/domain/wooms/exception/ex/WoomsUserNotEnrolledException.java
  src/main/java/com/ee06/wooms/domain/wooms/repository/WoomsRepository.java
  src/main/java/com/ee06/wooms/domain/wooms/service/WoomsService.java
  src/main/java/com/ee06/wooms/global/exception/ErrorCode.java
Labels: ✨ Feature

#51 Refactor : validation 에러 처리
  src/main/java/com/ee06/wooms/domain/wooms/repository/WoomsRepository.java
  src/main/java/com/ee06/wooms/global/exception/GlobalExceptionHandler.java
  src/main/java/com/ee06/wooms/global/util/ErrorCodeUtils.java
Labels: 🛠️ Refactor

#49 Feat : 사용자 검증, 예외처리
  src/main/java/com/ee06/wooms/domain/users/controller/UserController.java
  src/main/java/com/ee06/wooms/domain/users/dto/CustomUserDetails.java
  src/main/java/com/ee06/wooms/domain/users/dto/UserGameInfo.java
  src/main/java/com/ee06/wooms/domain/users/dto/auth/Join.java
  src/main/java/com/ee06/wooms/domain/users/dto/auth/Login.java
  src/main/java/com/ee06/wooms/domain/users/dto/auth/ModifyPasswordInfo.java
  src/main/java/com/ee06/wooms/domain/users/dto/auth/UserDto.java
  src/main/java/com/ee06/wooms/domain/users/dto/auth/UserGameInfo.java
  src/main/java/com/ee06/wooms/domain/users/dto/oauth/CustomOAuth2User.java
  src/main/java/com/ee06/wooms/domain/users/entity/Mail.java
  src/main/java/com/ee06/wooms/domain/users/exception/UserExceptionHandler.java
  src/main/java/com/ee06/wooms/domain/users/exception/ex/UserEmailCodeNotMatchedException.java
  src/main/java/com/ee06/wooms/domain/users/exception/ex/UserEmailExpiredException.java
  src/main/java/com/ee06/wooms/domain/users/exception/ex/UserEmailNotFoundException.java
  src/main/java/com/ee06/wooms/domain/users/exception/ex/UserExistException.java
  src/main/java/com/ee06/wooms/domain/users/exception/ex/UserNicknameTooLongException.java
  src/main/java/com/ee06/wooms/domain/users/exception/ex/UserNotSentEmailException.java
  src/main/java/com/ee06/wooms/domain/users/exception/ex/UserPasswordNotMatchedException.java
  src/main/java/com/ee06/wooms/domain/users/service/CustomOAuth2UserService.java
  src/main/java/com/ee06/wooms/domain/users/service/UserService.java
  src/main/java/com/ee06/wooms/global/config/SecurityConfig.java
  src/main/java/com/ee06/wooms/global/exception/ErrorCode.java
  src/main/java/com/ee06/wooms/global/jwt/JWTUtil.java
  src/main/java/com/ee06/wooms/global/jwt/controller/ReIssueController.java
  src/main/java/com/ee06/wooms/global/jwt/exception/CustomAuthenticationException.java
  src/main/java/com/ee06/wooms/global/jwt/exception/InvalidRefreshTokenException.java
  src/main/java/com/ee06/wooms/global/jwt/exception/InvalidTokenException.java
  src/main/java/com/ee06/wooms/global/jwt/filter/CustomLogoutFilter.java
  src/main/java/com/ee06/wooms/global/jwt/filter/JWTFilter.java
  src/main/java/com/ee06/wooms/global/jwt/filter/JwtAuthenticationEntryPoint.java
  src/main/java/com/ee06/wooms/global/jwt/filter/LoginFilter.java
  src/main/java/com/ee06/wooms/global/jwt/service/JwtService.java
  src/main/java/com/ee06/wooms/global/oauth/CustomSuccessHandler.java
  src/main/java/com/ee06/wooms/global/oauth/exception/NotFoundPlatformException.java
  src/main/java/com/ee06/wooms/global/util/RandomHelper.java
  src/main/java/com/ee06/wooms/global/util/RegExpUtils.java
Labels: ✨ Feature

#54 Feat : Wooms 참가 요청 거절, 승낙
  src/main/java/com/ee06/wooms/domain/enrollments/entity/Enrollment.java
  src/main/java/com/ee06/wooms/domain/wooms/controller/WoomsController.java
  src/main/java/com/ee06/wooms/domain/wooms/dto/WoomsEnrollRequest.java
  src/main/java/com/ee06/wooms/domain/wooms/exception/WoomsExceptionHandler.java
  src/main/java/com/ee06/wooms/domain/wooms/exception/ex/WoomsNotValidEnrollmentException.java
  src/main/java/com/ee06/wooms/domain/wooms/repository/WoomsRepository.java
  src/main/java/com/ee06/wooms/domain/wooms/service/WoomsService.java
  src/main/java/com/ee06/wooms/global/exception/ErrorCode.java
Labels: ✨ Feature

#57 Refactor : 토큰 재발급 시 claim null 수정
  src/main/java/com/ee06/wooms/domain/users/service/UserService.java
  src/main/java/com/ee06/wooms/global/config/SecurityConfig.java
  src/main/java/com/ee06/wooms/global/jwt/JWTUtil.java
  src/main/java/com/ee06/wooms/global/jwt/dto/RefreshToken.java
  src/main/java/com/ee06/wooms/global/jwt/filter/CustomLogoutFilter.java
  src/main/java/com/ee06/wooms/global/jwt/filter/JWTFilter.java
  src/main/java/com/ee06/wooms/global/jwt/filter/LoginFilter.java
  src/main/java/com/ee06/wooms/global/jwt/repository/RefreshTokenRepository.java
  src/main/java/com/ee06/wooms/global/jwt/service/JwtService.java
  src/main/java/com/ee06/wooms/global/oauth/CustomSuccessHandler.java
Labels: 🛠️ Refactor

#56 Feat : Wooms 관리자 위임
  src/main/java/com/ee06/wooms/domain/enrollments/repository/EnrollmentRepository.java
  src/main/java/com/ee06/wooms/domain/wooms/controller/WoomsController.java
  src/main/java/com/ee06/wooms/domain/wooms/dto/WoomsMandateAdminRequest.java
  src/main/java/com/ee06/wooms/domain/wooms/entity/Wooms.java
  src/main/java/com/ee06/wooms/domain/wooms/exception/WoomsExceptionHandler.java
  src/main/java/com/ee06/wooms/domain/wooms/exception/ex/WoomsNotValidException.java
  src/main/java/com/ee06/wooms/domain/wooms/repository/WoomsRepository.java
  src/main/java/com/ee06/wooms/domain/wooms/service/WoomsService.java
  src/main/java/com/ee06/wooms/global/exception/ErrorCode.java
Labels: ✨ Feature

#58 Feat : 방명록 기능 개발
  src/main/java/com/ee06/wooms/domain/comments/controller/CommentController.java
  src/main/java/com/ee06/wooms/domain/comments/dto/CommentRequest.java
  src/main/java/com/ee06/wooms/domain/comments/dto/CommentResponse.java
  src/main/java/com/ee06/wooms/domain/comments/entity/Comment.java
  src/main/java/com/ee06/wooms/domain/comments/exception/CommentExceptionHandler.java
  src/main/java/com/ee06/wooms/domain/comments/exception/ex/ExistWroteCommentException.java
  src/main/java/com/ee06/wooms/domain/comments/repository/CommentRepository.java
  src/main/java/com/ee06/wooms/domain/comments/service/CommentService.java
  src/main/java/com/ee06/wooms/domain/users/exception/UserExceptionHandler.java
  src/main/java/com/ee06/wooms/domain/wooms/exception/WoomsExceptionHandler.java
  src/main/java/com/ee06/wooms/global/config/SecurityConfig.java
  src/main/java/com/ee06/wooms/global/exception/ErrorCode.java
  src/test/java/com/ee06/wooms/domain/comments/controller/CommentControllerTest.java
Labels: ✨ Feature

#60 Feat : 빌드 이슈
  src/test/java/com/ee06/wooms/domain/comments/controller/CommentControllerTest.java
Labels: 🐛 Bug
